//// <auto-generated />
//using System;
//using DynamicWorkflow.Infrastructure.Identity;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace DynamicWorkflow.Infrastructure.Migrations
//{
//    [DbContext(typeof(ApplicationIdentityDbContext))]
//    [Migration("20251005084853_FixWorkflowStepsRename")]
//    partial class FixWorkflowStepsRename
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.9")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("ApplicationRoleApplicationUser", b =>
//                {
//                    b.Property<Guid>("RolesId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid>("UsersId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("RolesId", "UsersId");

//                    b.HasIndex("UsersId");

//                    b.ToTable("ApplicationRoleApplicationUser");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Department", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.HasKey("Id");

//                    b.ToTable("Departments", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.StepRole", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ActorName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("IsMandatory")
//                        .HasColumnType("bit");

//                    b.Property<string>("RoleName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("StepId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("StepId");

//                    b.ToTable("StepRoles");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Users.ApplicationRole", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Users.ApplicationUser", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("DeletionRequestedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<Guid>("DepartmentId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("DisplayName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<bool>("IsPendingDeletion")
//                        .HasColumnType("bit");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<Guid?>("ManagerId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("ProfilePicUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("RegisteredAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("DepartmentId");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkFlowInstanceStep", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Comments")
//                        .HasMaxLength(2000)
//                        .HasColumnType("nvarchar(2000)");

//                    b.Property<DateTime?>("CompletedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("InstanceId")
//                        .HasColumnType("int");

//                    b.Property<string>("PerformedByUserId")
//                        .HasMaxLength(500)
//                        .HasColumnType("nvarchar(500)");

//                    b.Property<string>("Status")
//                        .IsRequired()
//                        .ValueGeneratedOnAdd()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)")
//                        .HasDefaultValue("Pending");

//                    b.Property<int>("StepId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("InstanceId");

//                    b.HasIndex("StepId");

//                    b.ToTable("WorkFlowInstanceSteps", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Workflow", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreatedAt")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("datetime2")
//                        .HasDefaultValueSql("GETUTCDATE()");

//                    b.Property<string>("Description")
//                        .IsRequired()
//                        .HasMaxLength(1000)
//                        .HasColumnType("nvarchar(1000)");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<int>("Order")
//                        .HasColumnType("int");

//                    b.Property<int?>("ParentWorkflowId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.ToTable("Workflows", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowInstance", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("CurrentStepId")
//                        .HasColumnType("int");

//                    b.Property<int>("State")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasDefaultValue(5);

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("WorkflowId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("CurrentStepId");

//                    b.HasIndex("WorkflowId");

//                    b.ToTable("WorkflowInstances", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowStep", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("AssignedRole")
//                        .HasColumnType("int");

//                    b.Property<string>("Comments")
//                        .HasMaxLength(2000)
//                        .HasColumnType("nvarchar(2000)");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<int>("Order")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("WorkflowId")
//                        .HasColumnType("int");

//                    b.Property<bool>("isEndStep")
//                        .HasColumnType("bit");

//                    b.Property<int>("stepActionTypes")
//                        .HasColumnType("int");

//                    b.Property<int>("stepStatus")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("WorkflowId");

//                    b.ToTable("WorkflowSteps", (string)null);
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowTransition", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("Action")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("FromState")
//                        .HasColumnType("int");

//                    b.Property<int>("FromStepId")
//                        .HasColumnType("int");

//                    b.Property<string>("PerformedBy")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("Timestamp")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("ToState")
//                        .HasColumnType("int");

//                    b.Property<int>("ToStepId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("UpdatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("WorkflowId")
//                        .HasColumnType("int");

//                    b.Property<int?>("WorkflowInstanceId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("FromStepId");

//                    b.HasIndex("ToStepId");

//                    b.HasIndex("WorkflowId");

//                    b.HasIndex("WorkflowInstanceId");

//                    b.ToTable("WorkflowTransitions", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("RoleId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<Guid>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
//                {
//                    b.Property<Guid>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<Guid>("RoleId")
//                        .HasColumnType("uniqueidentifier");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
//                {
//                    b.Property<Guid>("UserId")
//                        .HasColumnType("uniqueidentifier");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens", (string)null);
//                });

//            modelBuilder.Entity("ApplicationRoleApplicationUser", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationRole", null)
//                        .WithMany()
//                        .HasForeignKey("RolesId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UsersId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.StepRole", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowStep", "Step")
//                        .WithMany("Roles")
//                        .HasForeignKey("StepId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Step");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Users.ApplicationUser", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Department", "Department")
//                        .WithMany("Users")
//                        .HasForeignKey("DepartmentId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.Navigation("Department");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkFlowInstanceStep", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowInstance", "Instance")
//                        .WithMany()
//                        .HasForeignKey("InstanceId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowStep", "Step")
//                        .WithMany("InstanceSteps")
//                        .HasForeignKey("StepId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.Navigation("Instance");

//                    b.Navigation("Step");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowInstance", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowStep", "CurrentStep")
//                        .WithMany()
//                        .HasForeignKey("CurrentStepId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.Workflow", "Workflow")
//                        .WithMany("Instances")
//                        .HasForeignKey("WorkflowId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("CurrentStep");

//                    b.Navigation("Workflow");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowStep", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Workflow", "workflow")
//                        .WithMany("Steps")
//                        .HasForeignKey("WorkflowId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("workflow");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowTransition", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowStep", "FromStep")
//                        .WithMany("OutgoingTransitions")
//                        .HasForeignKey("FromStepId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowStep", "ToStep")
//                        .WithMany("IncomingTransitions")
//                        .HasForeignKey("ToStepId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.Workflow", "workflow")
//                        .WithMany("Transitions")
//                        .HasForeignKey("WorkflowId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.WorkflowInstance", null)
//                        .WithMany("Transitions")
//                        .HasForeignKey("WorkflowInstanceId");

//                    b.Navigation("FromStep");

//                    b.Navigation("ToStep");

//                    b.Navigation("workflow");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
//                {
//                    b.HasOne("DynamicWorkflow.Core.Entities.Users.ApplicationUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Department", b =>
//                {
//                    b.Navigation("Users");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.Workflow", b =>
//                {
//                    b.Navigation("Instances");

//                    b.Navigation("Steps");

//                    b.Navigation("Transitions");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowInstance", b =>
//                {
//                    b.Navigation("Transitions");
//                });

//            modelBuilder.Entity("DynamicWorkflow.Core.Entities.WorkflowStep", b =>
//                {
//                    b.Navigation("IncomingTransitions");

//                    b.Navigation("InstanceSteps");

//                    b.Navigation("OutgoingTransitions");

//                    b.Navigation("Roles");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
